name: acme
description: Acme app is an app developed as a test for generating random generic products.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Injection and states
  provider: ^6.0.3
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # HTTP requests
  dio: ^4.0.6

  # Pie chart
  syncfusion_flutter_charts: ^20.2.50

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
